name: Weekly Update

on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * 0' # Run every Sunday morning

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install dependencies from Pipfile
        run: |
          pip install pipenv
          pipenv install --dev

      - name: Update useragents.txt
        run: |
          git config --global user.email "davidwittman@users.noreply.github.com"
          git config --global user.name "David Wittman"
          make scrape smoketest version

      - name: Push new tag
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          git push
          git push --tags
